name: FCR Processing Request
description: Upload FCR files for automated extraction and processing
title: "FCR Processing Request"
labels: ["fcr-processing"]
body:
  - type: markdown
    attributes:
      value: |
        ### Automated FCR Data Extraction
        
        Upload your FCR CSV or Excel files below. This service extracts:
        
        **AI-Powered Extraction:**
        - Shipper Name
        - Shipper Address
        
        **Column Extraction:**
        - Marks and Numbers (complete column data)
        - Cargo Description (complete column data)
        
        **Output:** Structured JSON and formatted text files
        
  - type: textarea
    id: file_upload
    attributes:
      label: File Upload
      description: Attach your FCR file(s) here - supports CSV and XLSX formats (max 25MB per file)
      placeholder: Drag and drop files here
    validations:
      required: true
